#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct ContactRecord {
    pub(crate) owner_did: String,
    pub(crate) did: String,
    pub(crate) name: String,
    pub(crate) handle: String,
    pub(crate) nick_name: String,
    pub(crate) bio: String,
    pub(crate) profile_md: String,
    pub(crate) tags: String,
    pub(crate) relationship: String,
    pub(crate) source_type: String,
    pub(crate) source_name: String,
    pub(crate) source_group_id: String,
    pub(crate) connected_at: String,
    pub(crate) recommended_reason: String,
    pub(crate) followed: Option<bool>,
    pub(crate) messaged: Option<bool>,
    pub(crate) note: String,
    pub(crate) first_seen_at: String,
    pub(crate) last_seen_at: String,
    pub(crate) metadata: String,
    pub(crate) credential_name: String,
}
