#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct GroupRecord {
    pub(crate) owner_identity_id: String,
    pub(crate) owner_did: String,
    pub(crate) group_id: String,
    pub(crate) group_did: String,
    pub(crate) name: String,
    pub(crate) group_mode: String,
    pub(crate) slug: String,
    pub(crate) description: String,
    pub(crate) goal: String,
    pub(crate) rules: String,
    pub(crate) message_prompt: String,
    pub(crate) doc_url: String,
    pub(crate) group_owner_did: String,
    pub(crate) group_owner_handle: String,
    pub(crate) my_role: String,
    pub(crate) membership_status: String,
    pub(crate) join_enabled: Option<bool>,
    pub(crate) join_code: String,
    pub(crate) join_code_expires_at: String,
    pub(crate) member_count: Option<i64>,
    pub(crate) last_synced_seq: Option<i64>,
    pub(crate) last_read_seq: Option<i64>,
    pub(crate) last_message_at: String,
    pub(crate) remote_created_at: String,
    pub(crate) remote_updated_at: String,
    pub(crate) stored_at: String,
    pub(crate) metadata: String,
    pub(crate) credential_name: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct GroupMemberRecord {
    pub(crate) owner_identity_id: String,
    pub(crate) owner_did: String,
    pub(crate) group_id: String,
    pub(crate) user_id: String,
    pub(crate) member_did: String,
    pub(crate) member_handle: String,
    pub(crate) profile_url: String,
    pub(crate) role: String,
    pub(crate) status: String,
    pub(crate) joined_at: String,
    pub(crate) sent_message_count: Option<i64>,
    pub(crate) last_synced_at: String,
    pub(crate) metadata: String,
    pub(crate) credential_name: String,
}
