#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

DRY_RUN=0
BUILD_IOS=1
BUILD_MACOS=1

usage() {
  cat <<'USAGE'
Usage: scripts/flutter/build-apple.sh [--dry-run] [--ios|--macos]

Builds both iOS and macOS Apple native artifacts by default.
Use --ios or --macos to validate/package only one platform family.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      ;;
    --ios)
      BUILD_IOS=1
      BUILD_MACOS=0
      ;;
    --macos)
      BUILD_IOS=0
      BUILD_MACOS=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
  shift
done

LIB_NAME="awiki_im_core"
IOS_FRAMEWORK_DIR="${ROOT_DIR}/packages/awiki_im_core/ios/Frameworks"
MACOS_FRAMEWORK_DIR="${ROOT_DIR}/packages/awiki_im_core/macos/Frameworks"
IOS_INCLUDE_DIR="${ROOT_DIR}/packages/awiki_im_core/ios/include"
MACOS_INCLUDE_DIR="${ROOT_DIR}/packages/awiki_im_core/macos/include"
IOS_XCFRAMEWORK="${IOS_FRAMEWORK_DIR}/AwikiImCore.xcframework"
MACOS_XCFRAMEWORK="${MACOS_FRAMEWORK_DIR}/AwikiImCore.xcframework"
IOS_TARGETS=(
  aarch64-apple-ios
  aarch64-apple-ios-sim
  x86_64-apple-ios
)
MACOS_TARGETS=(
  aarch64-apple-darwin
  x86_64-apple-darwin
)
TARGETS=()
if [[ "${BUILD_IOS}" == "1" ]]; then
  TARGETS+=("${IOS_TARGETS[@]}")
fi
if [[ "${BUILD_MACOS}" == "1" ]]; then
  TARGETS+=("${MACOS_TARGETS[@]}")
fi

if [[ "${DRY_RUN}" == "1" ]]; then
  echo "Would rustup target add: ${TARGETS[*]}"
  if [[ "${BUILD_IOS}" == "1" && "${BUILD_MACOS}" == "1" ]]; then
    echo "Would build staticlibs and create iOS/macOS XCFrameworks"
  elif [[ "${BUILD_IOS}" == "1" ]]; then
    echo "Would build staticlibs and create iOS XCFramework"
  else
    echo "Would build staticlibs and create macOS XCFramework"
  fi
  exit 0
fi

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "Apple build must run on macOS." >&2
  exit 1
fi

if ! xcodebuild -version >/dev/null 2>&1; then
  DEFAULT_XCODE_DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
  if [[ -z "${DEVELOPER_DIR:-}" && -d "${DEFAULT_XCODE_DEVELOPER_DIR}" ]]; then
    export DEVELOPER_DIR="${DEFAULT_XCODE_DEVELOPER_DIR}"
  fi
fi

if ! xcodebuild -version >/dev/null 2>&1; then
  echo "xcodebuild is required for Apple XCFramework packaging." >&2
  echo "Install full Xcode or set DEVELOPER_DIR to Xcode.app/Contents/Developer." >&2
  xcode-select -p >&2 || true
  exit 1
fi

if [[ "${BUILD_IOS}" == "1" ]]; then
  if ! xcrun --sdk iphoneos --show-sdk-path >/dev/null 2>&1; then
    echo "iPhoneOS SDK is required for iOS builds." >&2
    echo "Install full Xcode or set DEVELOPER_DIR to Xcode.app/Contents/Developer." >&2
    xcrun --sdk iphoneos --show-sdk-path >&2 || true
    exit 1
  fi
fi

rustup target add "${TARGETS[@]}"

for target in "${IOS_TARGETS[@]}"; do
  if [[ "${BUILD_IOS}" != "1" ]]; then
    continue
  fi
  cargo build \
    -p im-core-dart \
    --release \
    --target "${target}" \
    --no-default-features \
    --features blocking,sqlite,http,ios
done

for target in "${MACOS_TARGETS[@]}"; do
  if [[ "${BUILD_MACOS}" != "1" ]]; then
    continue
  fi
  cargo build \
    -p im-core-dart \
    --release \
    --target "${target}" \
    --no-default-features \
    --features blocking,sqlite,http,macos
done

mkdir -p "${IOS_FRAMEWORK_DIR}" "${MACOS_FRAMEWORK_DIR}" "${IOS_INCLUDE_DIR}" "${MACOS_INCLUDE_DIR}"
cat > "${IOS_INCLUDE_DIR}/awiki_im_core.h" <<'HEADER'
#pragma once
// The FFI symbols are generated by flutter_rust_bridge.
HEADER
cat > "${MACOS_INCLUDE_DIR}/awiki_im_core.h" <<'HEADER'
#pragma once
// The FFI symbols are generated by flutter_rust_bridge.
HEADER

if [[ "${BUILD_IOS}" == "1" ]]; then
  SIM_DIR="$(mktemp -d "${TMPDIR:-/tmp}/awiki-ios-sim.XXXXXX")"
  lipo -create \
    "target/aarch64-apple-ios-sim/release/lib${LIB_NAME}.a" \
    "target/x86_64-apple-ios/release/lib${LIB_NAME}.a" \
    -output "${SIM_DIR}/lib${LIB_NAME}.a"

  rm -rf "${IOS_XCFRAMEWORK}"
  xcodebuild -create-xcframework \
    -library "target/aarch64-apple-ios/release/lib${LIB_NAME}.a" \
    -headers "${IOS_INCLUDE_DIR}" \
    -library "${SIM_DIR}/lib${LIB_NAME}.a" \
    -headers "${IOS_INCLUDE_DIR}" \
    -output "${IOS_XCFRAMEWORK}"
fi

if [[ "${BUILD_MACOS}" == "1" ]]; then
  MACOS_DIR="$(mktemp -d "${TMPDIR:-/tmp}/awiki-macos.XXXXXX")"
  lipo -create \
    "target/aarch64-apple-darwin/release/lib${LIB_NAME}.a" \
    "target/x86_64-apple-darwin/release/lib${LIB_NAME}.a" \
    -output "${MACOS_DIR}/lib${LIB_NAME}.a"

  rm -rf "${MACOS_XCFRAMEWORK}"
  xcodebuild -create-xcframework \
    -library "${MACOS_DIR}/lib${LIB_NAME}.a" \
    -headers "${MACOS_INCLUDE_DIR}" \
    -output "${MACOS_XCFRAMEWORK}"
fi
