#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

DRY_RUN=0
BUILD_IOS=1
BUILD_MACOS=1

usage() {
  cat <<'USAGE'
Usage: scripts/flutter/build-apple.sh [--dry-run] [--ios|--macos]

Builds both iOS and macOS Apple native artifacts by default.
Use --ios or --macos to validate/package only one platform family.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      ;;
    --ios)
      BUILD_IOS=1
      BUILD_MACOS=0
      ;;
    --macos)
      BUILD_IOS=0
      BUILD_MACOS=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
  shift
done

LIB_NAME="awiki_im_core"
IOS_DEPLOYMENT_TARGET="${AWIKI_IOS_DEPLOYMENT_TARGET:-13.0}"
IOS_ARM64_SIMULATOR_DEPLOYMENT_TARGET="${AWIKI_IOS_ARM64_SIMULATOR_DEPLOYMENT_TARGET:-14.0}"
MACOS_X86_64_DEPLOYMENT_TARGET="${AWIKI_MACOS_X86_64_DEPLOYMENT_TARGET:-10.15}"
MACOS_ARM64_DEPLOYMENT_TARGET="${AWIKI_MACOS_ARM64_DEPLOYMENT_TARGET:-11.0}"
IOS_FRAMEWORK_DIR="${ROOT_DIR}/packages/awiki_im_core/ios/Frameworks"
MACOS_FRAMEWORK_DIR="${ROOT_DIR}/packages/awiki_im_core/macos/Frameworks"
IOS_INCLUDE_DIR="${ROOT_DIR}/packages/awiki_im_core/ios/include"
MACOS_INCLUDE_DIR="${ROOT_DIR}/packages/awiki_im_core/macos/include"
IOS_XCFRAMEWORK="${IOS_FRAMEWORK_DIR}/AwikiImCore.xcframework"
MACOS_XCFRAMEWORK="${MACOS_FRAMEWORK_DIR}/AwikiImCore.xcframework"
IOS_TARGETS=(
  aarch64-apple-ios
  aarch64-apple-ios-sim
  x86_64-apple-ios
)
MACOS_TARGETS=(
  aarch64-apple-darwin
  x86_64-apple-darwin
)
TARGETS=()
if [[ "${BUILD_IOS}" == "1" ]]; then
  TARGETS+=("${IOS_TARGETS[@]}")
fi
if [[ "${BUILD_MACOS}" == "1" ]]; then
  TARGETS+=("${MACOS_TARGETS[@]}")
fi

if [[ "${DRY_RUN}" == "1" ]]; then
  echo "Would rustup target add: ${TARGETS[*]}"
  echo "Would use iOS deployment target: ${IOS_DEPLOYMENT_TARGET}"
  echo "Would use iOS arm64 simulator deployment target: ${IOS_ARM64_SIMULATOR_DEPLOYMENT_TARGET}"
  echo "Would use macOS deployment targets: arm64=${MACOS_ARM64_DEPLOYMENT_TARGET}, x86_64=${MACOS_X86_64_DEPLOYMENT_TARGET}"
  if [[ "${BUILD_IOS}" == "1" && "${BUILD_MACOS}" == "1" ]]; then
    echo "Would build staticlibs and create iOS/macOS XCFrameworks"
  elif [[ "${BUILD_IOS}" == "1" ]]; then
    echo "Would build staticlibs and create iOS XCFramework"
  else
    echo "Would build staticlibs and create macOS XCFramework"
  fi
  exit 0
fi

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "Apple build must run on macOS." >&2
  exit 1
fi

if ! xcodebuild -version >/dev/null 2>&1; then
  DEFAULT_XCODE_DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
  if [[ -z "${DEVELOPER_DIR:-}" && -d "${DEFAULT_XCODE_DEVELOPER_DIR}" ]]; then
    export DEVELOPER_DIR="${DEFAULT_XCODE_DEVELOPER_DIR}"
  fi
fi

if ! xcodebuild -version >/dev/null 2>&1; then
  echo "xcodebuild is required for Apple XCFramework packaging." >&2
  echo "Install full Xcode or set DEVELOPER_DIR to Xcode.app/Contents/Developer." >&2
  xcode-select -p >&2 || true
  exit 1
fi

if [[ "${BUILD_IOS}" == "1" ]]; then
  if ! xcrun --sdk iphoneos --show-sdk-path >/dev/null 2>&1; then
    echo "iPhoneOS SDK is required for iOS builds." >&2
    echo "Install full Xcode or set DEVELOPER_DIR to Xcode.app/Contents/Developer." >&2
    xcrun --sdk iphoneos --show-sdk-path >&2 || true
    exit 1
  fi
fi

rustup target add "${TARGETS[@]}"

for target in "${IOS_TARGETS[@]}"; do
  if [[ "${BUILD_IOS}" != "1" ]]; then
    continue
  fi
  ios_cflags="-mios-simulator-version-min=${IOS_DEPLOYMENT_TARGET}"
  if [[ "${target}" == "aarch64-apple-ios" ]]; then
    ios_cflags="-miphoneos-version-min=${IOS_DEPLOYMENT_TARGET}"
  elif [[ "${target}" == "aarch64-apple-ios-sim" ]]; then
    ios_cflags="-mios-simulator-version-min=${IOS_ARM64_SIMULATOR_DEPLOYMENT_TARGET}"
  fi
  if [[ -n "${CFLAGS:-}" ]]; then
    ios_cflags="${CFLAGS} ${ios_cflags}"
  fi
  CFLAGS="${ios_cflags}" IPHONEOS_DEPLOYMENT_TARGET="${IOS_DEPLOYMENT_TARGET}" cargo build \
    -p im-core-dart \
    --release \
    --target "${target}" \
    --no-default-features \
    --features blocking,sqlite,http,ios
done

for target in "${MACOS_TARGETS[@]}"; do
  if [[ "${BUILD_MACOS}" != "1" ]]; then
    continue
  fi
  macos_deployment_target="${MACOS_X86_64_DEPLOYMENT_TARGET}"
  if [[ "${target}" == "aarch64-apple-darwin" ]]; then
    macos_deployment_target="${MACOS_ARM64_DEPLOYMENT_TARGET}"
  fi
  MACOSX_DEPLOYMENT_TARGET="${macos_deployment_target}" cargo build \
    -p im-core-dart \
    --release \
    --target "${target}" \
    --no-default-features \
    --features blocking,sqlite,http,macos
done

mkdir -p "${IOS_FRAMEWORK_DIR}" "${MACOS_FRAMEWORK_DIR}" "${IOS_INCLUDE_DIR}" "${MACOS_INCLUDE_DIR}"
cat > "${IOS_INCLUDE_DIR}/awiki_im_core.h" <<'HEADER'
#pragma once
// The FFI symbols are generated by flutter_rust_bridge.
HEADER
cat > "${MACOS_INCLUDE_DIR}/awiki_im_core.h" <<'HEADER'
#pragma once
// The FFI symbols are generated by flutter_rust_bridge.
HEADER

if [[ "${BUILD_IOS}" == "1" ]]; then
  SIM_DIR="$(mktemp -d "${TMPDIR:-/tmp}/awiki-ios-sim.XXXXXX")"
  lipo -create \
    "target/aarch64-apple-ios-sim/release/lib${LIB_NAME}.a" \
    "target/x86_64-apple-ios/release/lib${LIB_NAME}.a" \
    -output "${SIM_DIR}/lib${LIB_NAME}.a"

  verify_ios_archive() {
    local archive="$1"
    local arch="$2"
    local maximum_version="$3"
    local versions
    versions="$(xcrun otool -arch "${arch}" -l "${archive}" 2>/dev/null \
      | awk '/^[[:space:]]+(version|minos) / { print $2 }' \
      | sort -Vu)"
    if [[ -z "${versions}" ]]; then
      echo "No Mach-O deployment versions found in ${archive} (${arch})." >&2
      return 1
    fi
    while IFS= read -r version; do
      if awk -v actual="${version}" -v maximum="${maximum_version}" '
        function number(value, parts) {
          split(value, parts, ".")
          return (parts[1] + 0) * 1000000 + (parts[2] + 0) * 1000 + (parts[3] + 0)
        }
        BEGIN { exit !(number(actual) > number(maximum)) }
      '; then
        echo "${archive} (${arch}) contains minimum OS ${version}, above ${maximum_version}." >&2
        return 1
      fi
    done <<< "${versions}"
  }

  verify_ios_archive \
    "target/aarch64-apple-ios/release/lib${LIB_NAME}.a" \
    arm64 \
    "${IOS_DEPLOYMENT_TARGET}"
  verify_ios_archive \
    "${SIM_DIR}/lib${LIB_NAME}.a" \
    x86_64 \
    "${IOS_DEPLOYMENT_TARGET}"
  verify_ios_archive \
    "${SIM_DIR}/lib${LIB_NAME}.a" \
    arm64 \
    "${IOS_ARM64_SIMULATOR_DEPLOYMENT_TARGET}"

  rm -rf "${IOS_XCFRAMEWORK}"
  xcodebuild -create-xcframework \
    -library "target/aarch64-apple-ios/release/lib${LIB_NAME}.a" \
    -headers "${IOS_INCLUDE_DIR}" \
    -library "${SIM_DIR}/lib${LIB_NAME}.a" \
    -headers "${IOS_INCLUDE_DIR}" \
    -output "${IOS_XCFRAMEWORK}"
fi

if [[ "${BUILD_MACOS}" == "1" ]]; then
  MACOS_DIR="$(mktemp -d "${TMPDIR:-/tmp}/awiki-macos.XXXXXX")"
  lipo -create \
    "target/aarch64-apple-darwin/release/lib${LIB_NAME}.a" \
    "target/x86_64-apple-darwin/release/lib${LIB_NAME}.a" \
    -output "${MACOS_DIR}/lib${LIB_NAME}.a"

  rm -rf "${MACOS_XCFRAMEWORK}"
  xcodebuild -create-xcframework \
    -library "${MACOS_DIR}/lib${LIB_NAME}.a" \
    -headers "${MACOS_INCLUDE_DIR}" \
    -output "${MACOS_XCFRAMEWORK}"
fi
