#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

if ! command -v flutter_rust_bridge_codegen >/dev/null 2>&1; then
  echo "flutter_rust_bridge_codegen is required. Install with: cargo install flutter_rust_bridge_codegen --version 2.12.0" >&2
  exit 1
fi

flutter_rust_bridge_codegen generate \
  --rust-root "crates/im-core-dart" \
  --rust-input "crate::api" \
  --dart-output "packages/awiki_im_core/lib/src/generated" \
  --rust-output "crates/im-core-dart/src/frb_generated.rs"

python3 - <<'PY'
from pathlib import Path
import re

p = Path("crates/im-core-dart/src/frb_generated.rs")
s = p.read_text()

def ensure_core_import(match: re.Match[str]) -> str:
    block = match.group(0)
    indent = match.group("indent")
    if f"{indent}use crate::api::core::*;" in block:
        return block
    return block + f"{indent}use crate::api::core::*;\n"

s, replacements = re.subn(
    r"(?m)^(?P<indent>\s*)use crate::api::auth::\*;\n"
    r"(?P=indent)use crate::api::client::\*;\n"
    r"(?:(?P=indent)use crate::api::core::\*;\n)?",
    ensure_core_import,
    s,
)
if replacements == 0:
    raise RuntimeError("FRB generated imports no longer contain the auth/client import marker")

s = s.replace('#[unsafe(no_mangle)]', '#[no_mangle]')
io_boilerplate = '''    pub trait NewWithNullPtr {
        fn new_with_null_ptr() -> Self;
    }

    impl<T> NewWithNullPtr for *mut T {
        fn new_with_null_ptr() -> Self {
            std::ptr::null_mut()
        }
    }

    #[no_mangle]
    pub extern "C" fn frb_get_rust_content_hash() -> i32 {
        FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH
    }

    #[no_mangle]
    pub extern "C" fn frb_pde_ffi_dispatcher_primary(
        func_id: i32,
        port_: i64,
        ptr_: *mut u8,
        rust_vec_len_: i32,
        data_len_: i32,
    ) {
        pde_ffi_dispatcher_primary_impl(func_id, port_, ptr_, rust_vec_len_, data_len_)
    }

    #[no_mangle]
    pub extern "C" fn frb_pde_ffi_dispatcher_sync(
        func_id: i32,
        ptr_: *mut u8,
        rust_vec_len_: i32,
        data_len_: i32,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
        pde_ffi_dispatcher_sync_impl(func_id, ptr_, rust_vec_len_, data_len_)
    }

    #[no_mangle]
    pub extern "C" fn frb_dart_fn_deliver_output(
        call_id: i32,
        ptr_: *mut u8,
        rust_vec_len_: i32,
        data_len_: i32,
    ) {
        let message = unsafe {
            flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                ptr_,
                rust_vec_len_,
                data_len_,
            )
        };
        FLUTTER_RUST_BRIDGE_HANDLER.dart_fn_handle_output(call_id, message)
    }'''
if "flutter_rust_bridge::frb_generated_boilerplate_io!();" not in s:
    raise RuntimeError("FRB generated IO boilerplate marker was not found")
s = s.replace('flutter_rust_bridge::frb_generated_boilerplate_io!();', io_boilerplate.strip(), 1)
p.write_text(s)
PY

cat > "packages/awiki_im_core/lib/src/generated/bridge_generated.dart" <<'BRIDGE'
// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

export 'frb_generated.dart';
BRIDGE

python3 - <<'PY'
from pathlib import Path

for path in [Path("crates/im-core-dart/src/frb_generated.rs"), *Path("packages/awiki_im_core/lib/src/generated").rglob("*.dart")]:
    text = path.read_text()
    path.write_text("\n".join(line.rstrip() for line in text.splitlines()) + "\n")
PY

rustfmt "crates/im-core-dart/src/frb_generated.rs"
