#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

if ! command -v flutter_rust_bridge_codegen >/dev/null 2>&1; then
  echo "flutter_rust_bridge_codegen is required. Install with: cargo install flutter_rust_bridge_codegen --version 2.12.0" >&2
  exit 1
fi

flutter_rust_bridge_codegen generate \
  --rust-root "crates/im-core-dart" \
  --rust-input "crate::api" \
  --dart-output "packages/awiki_im_core/lib/src/generated" \
  --rust-output "crates/im-core-dart/src/frb_generated.rs"

python3 - <<'PY'
from pathlib import Path
import re

p = Path("crates/im-core-dart/src/frb_generated.rs")
s = p.read_text()

# FRB can emit adjacent imports on the same line when rustfmt fails on its
# temporary `#[unsafe(no_mangle)]` output. Normalize those first so the import
# patch below remains stable across generated API additions.
s = s.replace(";use ", ";\nuse ")

CANONICAL_API_IMPORTS = [
    "use crate::api::attachments::*;",
    "use crate::api::client::*;",
    "use crate::api::core::DartImCore;",
    "use crate::api::core::*;",
    "use crate::api::realtime::*;",
]
API_IMPORT_RE = re.compile(
    r"^use crate::api::(?:attachments::\*|client::\*|core::(?:DartImCore|\*)|realtime::\*);$"
)

def normalize_import_section(match: re.Match[str]) -> str:
    indent = match.group("indent")
    body = match.group("body")
    saw_super = False
    remaining_lines = []

    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped == "use super::*;":
            saw_super = True
            continue
        if API_IMPORT_RE.match(stripped):
            continue
        remaining_lines.append(line.rstrip())

    normalized_lines = []
    if saw_super:
        normalized_lines.append(f"{indent}use super::*;")
    normalized_lines.extend(f"{indent}{import_line}" for import_line in CANONICAL_API_IMPORTS)
    normalized_lines.extend(remaining_lines)

    return match.group("header") + "\n" + "\n".join(normalized_lines) + "\n\n"

s, replacements = re.subn(
    r"(?ms)^(?P<header>(?P<indent>[ \t]*)// Section: imports\n)(?P<body>.*?)(?=^[ \t]*// Section: boilerplate\n)",
    normalize_import_section,
    s,
)
if replacements == 0:
    raise RuntimeError("FRB generated import sections were not found")

s = s.replace('#[unsafe(no_mangle)]', '#[no_mangle]')
io_boilerplate = '''    pub trait NewWithNullPtr {
        fn new_with_null_ptr() -> Self;
    }

    impl<T> NewWithNullPtr for *mut T {
        fn new_with_null_ptr() -> Self {
            std::ptr::null_mut()
        }
    }

    #[no_mangle]
    pub extern "C" fn frb_get_rust_content_hash() -> i32 {
        FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH
    }

    #[no_mangle]
    pub extern "C" fn frb_pde_ffi_dispatcher_primary(
        func_id: i32,
        port_: i64,
        ptr_: *mut u8,
        rust_vec_len_: i32,
        data_len_: i32,
    ) {
        pde_ffi_dispatcher_primary_impl(func_id, port_, ptr_, rust_vec_len_, data_len_)
    }

    #[no_mangle]
    pub extern "C" fn frb_pde_ffi_dispatcher_sync(
        func_id: i32,
        ptr_: *mut u8,
        rust_vec_len_: i32,
        data_len_: i32,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
        pde_ffi_dispatcher_sync_impl(func_id, ptr_, rust_vec_len_, data_len_)
    }

    #[no_mangle]
    pub extern "C" fn frb_dart_fn_deliver_output(
        call_id: i32,
        ptr_: *mut u8,
        rust_vec_len_: i32,
        data_len_: i32,
    ) {
        let message = unsafe {
            flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                ptr_,
                rust_vec_len_,
                data_len_,
            )
        };
        FLUTTER_RUST_BRIDGE_HANDLER.dart_fn_handle_output(call_id, message)
    }'''
if "flutter_rust_bridge::frb_generated_boilerplate_io!();" not in s:
    raise RuntimeError("FRB generated IO boilerplate marker was not found")
s = s.replace('flutter_rust_bridge::frb_generated_boilerplate_io!();', io_boilerplate.strip(), 1)
p.write_text(s)
PY

cat > "packages/awiki_im_core/lib/src/generated/bridge_generated.dart" <<'BRIDGE'
// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

export 'frb_generated.dart';
BRIDGE

python3 - <<'PY'
from pathlib import Path

for path in [Path("crates/im-core-dart/src/frb_generated.rs"), *Path("packages/awiki_im_core/lib/src/generated").rglob("*.dart")]:
    text = path.read_text()
    path.write_text("\n".join(line.rstrip() for line in text.splitlines()) + "\n")
PY

rustfmt "crates/im-core-dart/src/frb_generated.rs"
